version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Accum
  - argmax
  - argmin
  - badzstd
  - bytemuck
  - cdylib
  - CUDA
  - cvtepi
  - cvtps
  - ddof
  - DTYPE
  - einsum
  - elems
  - Embedder
  - embedders
  - entr
  - hyperslab
  - hyperslabs
  - indicatif
  - inmem
  - libhdf
  - libnetcdf
  - loadu
  - matmul
  - maturin
  - mdformat
  - memcpy
  - metas
  - metno
  - movehl
  - multichunk
  - ndim
  - nelem
  - proptest
  - qhist
  - reprojection
  - rkyv
  - roundtrips
  - rustdoc
  - setzero
  - storeu
  - subslices
  - sumsq
  - TETR
  - Tetration
  - thiserror
  - THST
  - TIDX
  - trunc
  - unpackhi
  - vaddvq
  - vcvt
  - vget
  - vmulq
  - zstd
ignoreWords: []
import: []
