version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Accum
  - badzstd
  - bytemuck
  - cdylib
  - CUDA
  - cvtps
  - ddof
  - DTYPE
  - elems
  - embedders
  - hyperslab
  - hyperslabs
  - indicatif
  - inmem
  - loadu
  - maturin
  - mdformat
  - memcpy
  - metno
  - movehl
  - multichunk
  - ndim
  - nelem
  - proptest
  - reprojection
  - rkyv
  - rustdoc
  - storeu
  - sumsq
  - TETR
  - Tetration
  - thiserror
  - TIDX
  - trunc
  - vaddvq
  - vcvt
  - vget
  - vmulq
  - zstd
ignoreWords: []
import: []
